name    'radeksimko/smokeping'
version '0.1.0'
source 'https://github.com/radeksimko/puppet-smokeping.git'
author 'radeksimko'
license 'Apache License, Version 2.0'
summary 'Module for installing and configuring Smokeping'
description 'Module for installing and configuring Smokeping from Tobi Oetiker'
project_page 'https://github.com/radeksimko/puppet-smokeping'
